-- Esquema inicial de CEAVital en PostgreSQL.
--
-- Es el estado final de las 25 migraciones de la epoca SQLite (001-025), en un
-- solo archivo. Convenciones de esta traduccion:
--  * Fechas/horas: TIMESTAMP(0) en UTC (sin zona, a segundos), igual que el
--    CURRENT_TIMESTAMP de SQLite. connection.js las devuelve como texto
--    "YYYY-MM-DD HH:MM:SS", el mismo formato que ya esperaba todo el codigo.
--  * Ids: IDENTITY "by default" (permite copiar ids reales al migrar datos).
--  * Montos en pesos enteros: BIGINT (un INTEGER de Postgres llega a ~2.100
--    millones, poco para totales de pedidos grandes). Cantidades y flags 0/1: INTEGER.
--  * Se eliminaron las columnas de texto libre heredadas (productos.categoria,
--    productos.unidad_medida, clientes_empresa.condicion_pago): las reemplazan
--    las claves foraneas a los catalogos.
--  * COLLATE NOCASE de SQLite -> indices unicos sobre LOWER(columna).

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  usuario TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'encargado', 'cajero')),
  intentos_fallidos INTEGER NOT NULL DEFAULT 0,
  bloqueado_hasta TIMESTAMP(0),
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX idx_usuarios_usuario_activo ON usuarios(usuario) WHERE eliminado_en IS NULL;

CREATE TABLE sesiones_activas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'encargado', 'cajero')),
  token TEXT NOT NULL UNIQUE,
  estado TEXT NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'cerrada')),
  motivo_cierre TEXT CHECK (motivo_cierre IN ('logout', 'expulsada', 'timeout')),
  iniciada_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  ultima_actividad TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  cerrada_en TIMESTAMP(0)
);
-- Una sola sesion activa por rol: sostiene el lock de concurrencia.
CREATE UNIQUE INDEX idx_sesiones_activas_rol_activa ON sesiones_activas(rol) WHERE estado = 'activa';
CREATE INDEX idx_sesiones_activas_usuario ON sesiones_activas(usuario_id);

CREATE TABLE proveedores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  telefono TEXT,
  email TEXT,
  condicion_pago TEXT,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

-- Catalogos (nombre unico entre activos, sin distinguir mayusculas)
CREATE TABLE categorias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX idx_categorias_nombre_activo ON categorias(LOWER(nombre)) WHERE eliminado_en IS NULL;

CREATE TABLE unidades_medida (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX idx_unidades_medida_nombre_activo ON unidades_medida(LOWER(nombre)) WHERE eliminado_en IS NULL;

CREATE TABLE condiciones_pago (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX idx_condiciones_pago_nombre_activo ON condiciones_pago(LOWER(nombre)) WHERE eliminado_en IS NULL;

CREATE TABLE productos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  codigo_barras TEXT,
  precio_costo BIGINT NOT NULL,
  precio_venta BIGINT NOT NULL,
  proveedor_id INTEGER REFERENCES proveedores(id),
  stock_minimo INTEGER NOT NULL DEFAULT 0,
  dias_aviso_vencimiento INTEGER,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  categoria_id INTEGER REFERENCES categorias(id),
  unidad_medida_id INTEGER NOT NULL REFERENCES unidades_medida(id)
);
CREATE UNIQUE INDEX idx_productos_codigo_barras_activo ON productos(codigo_barras)
  WHERE codigo_barras IS NOT NULL AND eliminado_en IS NULL;
CREATE INDEX idx_productos_proveedor ON productos(proveedor_id);
CREATE INDEX idx_productos_categoria ON productos(categoria_id);
CREATE INDEX idx_productos_unidad_medida ON productos(unidad_medida_id);

CREATE TABLE lotes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INTEGER NOT NULL REFERENCES productos(id),
  cantidad INTEGER NOT NULL,
  fecha_ingreso DATE NOT NULL,
  fecha_vencimiento DATE,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_lotes_producto ON lotes(producto_id);
CREATE INDEX idx_lotes_fefo ON lotes(producto_id, fecha_vencimiento, fecha_ingreso);

CREATE TABLE clientes_empresa (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social TEXT NOT NULL,
  cuit TEXT,
  contacto_nombre TEXT,
  telefono TEXT,
  email TEXT,
  direccion TEXT,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  condicion_pago_id INTEGER REFERENCES condiciones_pago(id),
  portal_usuario TEXT,
  portal_password_hash TEXT,
  portal_habilitado INTEGER NOT NULL DEFAULT 0,
  portal_intentos_fallidos INTEGER NOT NULL DEFAULT 0,
  portal_bloqueado_hasta TIMESTAMP(0),
  portal_ultimo_acceso TIMESTAMP(0)
);
CREATE UNIQUE INDEX idx_clientes_empresa_cuit ON clientes_empresa(cuit)
  WHERE cuit IS NOT NULL AND eliminado_en IS NULL;
CREATE INDEX idx_clientes_empresa_condicion_pago ON clientes_empresa(condicion_pago_id);
CREATE UNIQUE INDEX idx_clientes_empresa_portal_usuario ON clientes_empresa(LOWER(portal_usuario))
  WHERE portal_usuario IS NOT NULL AND eliminado_en IS NULL;

CREATE TABLE ventas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  medio_pago TEXT NOT NULL CHECK (
    medio_pago IN ('efectivo', 'tarjeta', 'transferencia_qr', 'mercado_pago', 'fiado', 'cta_cte')
  ),
  cliente_empresa_id INTEGER REFERENCES clientes_empresa(id),
  total BIGINT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'registrada' CHECK (estado IN ('registrada', 'anulada')),
  anulada_por INTEGER REFERENCES usuarios(id),
  anulada_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_ventas_usuario ON ventas(usuario_id);
CREATE INDEX idx_ventas_creado_en ON ventas(creado_en);
CREATE INDEX idx_ventas_cliente_empresa ON ventas(cliente_empresa_id);

CREATE TABLE venta_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id INTEGER NOT NULL REFERENCES ventas(id),
  producto_id INTEGER NOT NULL REFERENCES productos(id),
  lote_id INTEGER NOT NULL REFERENCES lotes(id),
  cantidad INTEGER NOT NULL,
  precio_unitario BIGINT NOT NULL,
  subtotal BIGINT NOT NULL
);
CREATE INDEX idx_venta_items_venta ON venta_items(venta_id);
CREATE INDEX idx_venta_items_lote ON venta_items(lote_id);

-- Ledger insert-only: una fila mal cargada se corrige con un AJUSTE, nunca se edita ni se borra.
CREATE TABLE cuenta_corriente_movimientos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_empresa_id INTEGER NOT NULL REFERENCES clientes_empresa(id),
  tipo TEXT NOT NULL CHECK (tipo IN ('CARGO', 'PAGO', 'AJUSTE')),
  monto BIGINT NOT NULL,
  descripcion TEXT,
  venta_id INTEGER REFERENCES ventas(id),
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_ccm_cliente_empresa ON cuenta_corriente_movimientos(cliente_empresa_id);
CREATE INDEX idx_ccm_venta ON cuenta_corriente_movimientos(venta_id);

CREATE TABLE pedidos_proveedor (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_id INTEGER NOT NULL REFERENCES proveedores(id),
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  estado TEXT NOT NULL CHECK (estado IN ('realizado', 'pendiente', 'recibido', 'cancelado')),
  fecha DATE NOT NULL,
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_pedidos_proveedor_proveedor ON pedidos_proveedor(proveedor_id);

CREATE TABLE pedido_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id INTEGER NOT NULL REFERENCES pedidos_proveedor(id),
  producto_id INTEGER NOT NULL REFERENCES productos(id),
  cantidad INTEGER NOT NULL
);
CREATE INDEX idx_pedido_items_pedido ON pedido_items(pedido_id);

CREATE TABLE cierres_caja (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  fecha DATE NOT NULL,
  total_efectivo_esperado BIGINT NOT NULL,
  total_efectivo_contado BIGINT NOT NULL,
  diferencia_efectivo BIGINT NOT NULL,
  total_tarjeta BIGINT NOT NULL,
  total_transferencia_qr BIGINT NOT NULL,
  total_mercado_pago BIGINT NOT NULL,
  total_fiado BIGINT NOT NULL,
  total_general BIGINT NOT NULL,
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  fondo_dejado BIGINT NOT NULL DEFAULT 0,
  fondo_heredado BIGINT NOT NULL DEFAULT 0,
  total_gastos BIGINT NOT NULL DEFAULT 0,
  total_cta_cte BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE backups_historial (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destino TEXT NOT NULL CHECK (destino IN ('local', 'usb', 'nube')),
  estado TEXT NOT NULL CHECK (estado IN ('exito', 'error')),
  tamano_bytes BIGINT,
  mensaje_error TEXT,
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE configuracion (
  clave TEXT PRIMARY KEY,
  valor TEXT NOT NULL,
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE gastos_caja (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  concepto TEXT NOT NULL,
  monto BIGINT NOT NULL,
  proveedor_id INTEGER REFERENCES proveedores(id),
  eliminado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_gastos_caja_creado_en ON gastos_caja(creado_en);
CREATE INDEX idx_gastos_caja_proveedor ON gastos_caja(proveedor_id);

CREATE TABLE sesiones_cliente (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_empresa_id INTEGER NOT NULL REFERENCES clientes_empresa(id),
  token TEXT NOT NULL UNIQUE,
  estado TEXT NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'cerrada')),
  motivo_cierre TEXT,
  iniciada_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  ultima_actividad TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  cerrada_en TIMESTAMP(0)
);
CREATE INDEX idx_sesiones_cliente_cliente ON sesiones_cliente(cliente_empresa_id, estado);

CREATE TABLE pedidos_cliente (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_empresa_id INTEGER NOT NULL REFERENCES clientes_empresa(id),
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobado', 'rechazado', 'cancelado')),
  total BIGINT NOT NULL DEFAULT 0,
  observaciones TEXT,
  motivo_rechazo TEXT,
  venta_id INTEGER REFERENCES ventas(id),
  resuelto_por INTEGER REFERENCES usuarios(id),
  resuelto_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_pedidos_cliente_cliente ON pedidos_cliente(cliente_empresa_id);
CREATE INDEX idx_pedidos_cliente_estado ON pedidos_cliente(estado);

CREATE TABLE pedido_cliente_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id INTEGER NOT NULL REFERENCES pedidos_cliente(id),
  producto_id INTEGER NOT NULL REFERENCES productos(id),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario BIGINT NOT NULL,
  subtotal BIGINT NOT NULL
);
CREATE INDEX idx_pedido_cliente_items_pedido ON pedido_cliente_items(pedido_id);
CREATE INDEX idx_pedido_cliente_items_producto ON pedido_cliente_items(producto_id);
