-- Superadmin de la instalación (ruta /sa). Aditiva: no toca ninguna tabla existente.
-- Es la cuenta de CEA sobre ESTA instancia; no tiene nada que ver con los usuarios del
-- negocio (tabla `usuarios`): otra tabla, otra sesión, otra cookie.

CREATE TABLE superadmin (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  intentos_fallidos INTEGER NOT NULL DEFAULT 0,
  bloqueado_hasta TIMESTAMP(0),
  ultimo_acceso TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX idx_superadmin_usuario ON superadmin (LOWER(usuario));

-- csrf_token: secreto propio de cada sesión; toda acción que modifica algo lo exige
-- en el encabezado X-CSRF-Token (ver middleware/superadmin-auth.middleware.js).
CREATE TABLE sesiones_superadmin (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  superadmin_id INTEGER NOT NULL REFERENCES superadmin(id),
  token TEXT NOT NULL UNIQUE,
  csrf_token TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'cerrada')),
  motivo_cierre TEXT,
  iniciada_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  ultima_actividad TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  cerrada_en TIMESTAMP(0)
);
CREATE INDEX idx_sesiones_superadmin_estado ON sesiones_superadmin(estado);

-- Estado de la instalación: una sola fila (id = 1). El plan sigue en `configuracion`
-- (clave 'plan'), que es de donde ya lo lee el interruptor de módulos.
CREATE TABLE instancia (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  estado TEXT NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'suspendida')),
  motivo_suspension TEXT,
  suspendida_en TIMESTAMP(0),
  cuota_vence DATE,
  cuota_aviso_dias INTEGER NOT NULL DEFAULT 15 CHECK (cuota_aviso_dias BETWEEN 0 AND 365),
  actualizado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
INSERT INTO instancia (id) VALUES (1);

-- Registro de acciones de CEA sobre la instancia. Solo se agrega, nunca se edita ni se borra.
CREATE TABLE superadmin_acciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  superadmin_id INTEGER REFERENCES superadmin(id),
  accion TEXT NOT NULL,
  detalle TEXT,
  ip TEXT,
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_superadmin_acciones_fecha ON superadmin_acciones(creado_en DESC);
