-- Avisos de cuota por mail (superadmin). Aditiva.

-- A quién se le avisa (el mail de la empresa contratante). Vacío = no se manda nada.
ALTER TABLE instancia ADD COLUMN empresa_email TEXT;

-- Qué avisos ya se mandaron, para no repetirlos: uno por tipo y por fecha de vencimiento.
-- Al cargar una cuota nueva (otra fecha) los avisos vuelven a empezar solos.
CREATE TABLE cuota_avisos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('por_vencer', 'vence_hoy', 'vencida')),
  cuota_vence DATE NOT NULL,
  destinatario TEXT NOT NULL,
  enviado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  UNIQUE (tipo, cuota_vence)
);
