-- Defensa activa por IP (ver services/defensa-ip.service.js).
-- ips_bloqueadas: un renglón por cada bloqueo (el historial sirve para escalar la
-- duración ante la reincidencia). Activo = bloqueada_hasta futuro y sin liberada_en.
-- eventos_seguridad: cada detección (se purga a los 30 días desde el servidor).
CREATE TABLE ips_bloqueadas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip TEXT NOT NULL,
  motivo TEXT NOT NULL,
  detalle TEXT,
  reincidencia INTEGER NOT NULL DEFAULT 1,
  bloqueada_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  bloqueada_hasta TIMESTAMP(0) NOT NULL,
  liberada_en TIMESTAMP(0),
  origen TEXT NOT NULL DEFAULT 'automatico' CHECK (origen IN ('automatico', 'manual'))
);
CREATE INDEX idx_ips_bloqueadas_ip ON ips_bloqueadas (ip, bloqueada_en DESC);

CREATE TABLE eventos_seguridad (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  ip TEXT NOT NULL,
  tipo TEXT NOT NULL,
  metodo TEXT,
  ruta TEXT,
  user_agent TEXT,
  bloqueo BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_eventos_seguridad_creado ON eventos_seguridad (creado_en DESC);
