-- Historial de backups automaticos (ver src/bkps/). En produccion guarda lo que informa la app
-- de backups (para mostrar "estado del ultimo backup" en el panel del superadmin); en la app de
-- backups guarda sus propias corridas. No viaja en los backups (backup-completo.service.js).
CREATE TABLE backup_corridas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iniciada_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  terminada_en TIMESTAMP(0),
  resultado TEXT NOT NULL CHECK (resultado IN ('ok', 'error')),
  archivo TEXT,
  bytes BIGINT,
  filas BIGINT,
  verificado BOOLEAN NOT NULL DEFAULT FALSE,
  drive TEXT NOT NULL DEFAULT 'no_configurado' CHECK (drive IN ('subido', 'no_configurado', 'error')),
  detalle TEXT,
  origen TEXT NOT NULL DEFAULT 'local' CHECK (origen IN ('local', 'informada'))
);
CREATE INDEX idx_backup_corridas_iniciada ON backup_corridas (iniciada_en DESC);
