-- Tope de envios del acceso al portal por mail: hasta 5 por cliente y por hora (decision del
-- usuario, 2026-09-26), para que el boton "Enviar por mail" no sirva para llenarle la casilla al
-- cliente. Se anota cada envio para poder contarlos; uno que fallo en el SMTP queda marcado en
-- fallido_en y no cuenta para el tope. Aditiva: tabla nueva, no toca ningun dato existente.
CREATE TABLE envios_acceso_portal (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_empresa_id INTEGER NOT NULL REFERENCES clientes_empresa(id),
  enviado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  fallido_en TIMESTAMP(0)
);
CREATE INDEX idx_envios_acceso_portal_cliente ON envios_acceso_portal (cliente_empresa_id, enviado_en);
