-- Historial de pagos de la cuota (superadmin /sa). Aditiva: tabla nueva y una columna nueva en
-- `instancia`, que se completa a partir del vencimiento ya cargado (no cambia ningun dato existente).
--
-- Anotar un pago corre el vencimiento de la cuota los meses que cubre, contando SIEMPRE desde el
-- vencimiento y no desde el dia en que se pago (decision del usuario, 2026-09-26: "vence el 10,
-- paga el 15, el conteo sigue arrancando el 10"). cuota_dia_vence guarda ese dia fijo para que
-- un vencimiento el 31 no se vaya corriendo al 28/30 mes a mes.
ALTER TABLE instancia ADD COLUMN cuota_dia_vence SMALLINT CHECK (cuota_dia_vence BETWEEN 1 AND 31);
UPDATE instancia SET cuota_dia_vence = EXTRACT(DAY FROM cuota_vence) WHERE cuota_vence IS NOT NULL;

-- periodo_desde/periodo_hasta: el vencimiento antes y despues de anotar el pago (lo que cubre).
-- Un pago no se borra ni se edita: si se cargo mal se anula (anulado_en + motivo) y el vencimiento
-- vuelve atras los meses que habia corrido.
CREATE TABLE pagos_cuota (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_pago DATE NOT NULL,
  monto BIGINT NOT NULL CHECK (monto > 0),
  meses SMALLINT NOT NULL CHECK (meses BETWEEN 1 AND 12),
  periodo_desde DATE NOT NULL,
  periodo_hasta DATE NOT NULL,
  medio_pago TEXT NOT NULL CHECK (medio_pago IN ('transferencia', 'efectivo', 'mercado_pago', 'tarjeta', 'otro')),
  comprobante TEXT,
  nota TEXT,
  anulado_en TIMESTAMP(0),
  anulado_motivo TEXT,
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_pagos_cuota_fecha ON pagos_cuota (fecha_pago DESC, id DESC);
