-- Usuarios del negocio: topes por rol, email verificado con codigo y 2FA por mail (decisiones del
-- usuario, 2026-09-26). Aditiva: columnas y tablas nuevas; no borra ni modifica ningun dato.

-- Topes por rol que carga el superadmin al armar la empresa. NULL = todavia sin cargar: el Admin
-- no puede crear usuarios de ese rol (los que ya existen siguen funcionando).
ALTER TABLE instancia ADD COLUMN cupo_admin INTEGER CHECK (cupo_admin BETWEEN 0 AND 999);
ALTER TABLE instancia ADD COLUMN cupo_encargado INTEGER CHECK (cupo_encargado BETWEEN 0 AND 999);
ALTER TABLE instancia ADD COLUMN cupo_cajero INTEGER CHECK (cupo_cajero BETWEEN 0 AND 999);

-- Email de cada usuario (los nuevos entran con el: usuario = email). Se verifica con un codigo
-- que le llega la primera vez que entra; dos_fa = pedir ese codigo al entrar (una vez por dia
-- en cada dispositivo). Los usuarios que ya existen quedan sin email y entran como antes.
ALTER TABLE usuarios ADD COLUMN email TEXT;
ALTER TABLE usuarios ADD COLUMN email_verificado_en TIMESTAMP(0);
ALTER TABLE usuarios ADD COLUMN dos_fa BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX idx_usuarios_email_activo ON usuarios (LOWER(email)) WHERE email IS NOT NULL AND eliminado_en IS NULL;

-- Una sesion activa por USUARIO (antes una por ROL, regla de cuando el sistema iba a ser local:
-- con varios cajeros, el segundo expulsaba al primero). Si el mismo usuario entra desde otro
-- lado, se cierra su sesion anterior. Con la regla vieja nunca pudo haber dos sesiones activas
-- del mismo usuario, asi que el indice nuevo se crea sin conflicto.
DROP INDEX IF EXISTS idx_sesiones_activas_rol_activa;
CREATE UNIQUE INDEX idx_sesiones_activas_usuario_activa ON sesiones_activas (usuario_id) WHERE estado = 'activa';

-- Codigos de ingreso por mail (6 digitos, 10 minutos, 5 intentos). Se guardan solo hashes: el
-- "desafio" identifica el ingreso en curso (contrasena ya validada) y el codigo es lo que llego
-- por mail. usado_en marca el que ya sirvio; nunca se borran.
CREATE TABLE codigos_ingreso (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  desafio_hash TEXT NOT NULL UNIQUE,
  codigo_hash TEXT NOT NULL,
  enviado_a TEXT NOT NULL,
  intentos INTEGER NOT NULL DEFAULT 0,
  envios INTEGER NOT NULL DEFAULT 1,
  expira_en TIMESTAMP(0) NOT NULL,
  ultimo_envio_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  usado_en TIMESTAMP(0),
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE INDEX idx_codigos_ingreso_usuario ON codigos_ingreso (usuario_id);

-- Dispositivos (navegadores) donde un usuario con 2FA ya puso el codigo: no se le vuelve a pedir
-- ahi hasta expira_en (24 h). El navegador guarda un identificador en la cookie "dispositivo";
-- aca va su hash. Un mismo navegador sirve para varios usuarios (una PC compartida de la caja).
CREATE TABLE dispositivos_2fa (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  dispositivo_hash TEXT NOT NULL,
  expira_en TIMESTAMP(0) NOT NULL,
  creado_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
  UNIQUE (usuario_id, dispositivo_hash)
);
