import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import db, { pool } from './connection.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = path.join(__dirname, 'migrations');

// Clave del candado de Postgres que evita que dos instancias migren a la vez
// (ej. dos contenedores arrancando juntos en un deploy).
const CLAVE_CANDADO = 727_001;

/**
 * Aplica las migraciones .sql pendientes, en orden por nombre de archivo.
 * Idempotente: una migracion ya aplicada nunca se vuelve a correr. Cada
 * archivo corre en su propia transaccion (Postgres tiene DDL transaccional,
 * asi que una migracion que falla no deja nada a medias).
 */
export async function runMigrations() {
  const client = await pool.connect();
  try {
    await client.query('SELECT pg_advisory_lock($1)', [CLAVE_CANDADO]);

    await client.query(`
      CREATE TABLE IF NOT EXISTS _migrations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        archivo TEXT NOT NULL UNIQUE,
        aplicada_en TIMESTAMP(0) NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
      )
    `);

    const yaAplicadas = new Set(
      (await client.query('SELECT archivo FROM _migrations')).rows.map((fila) => fila.archivo)
    );

    const archivos = fs
      .readdirSync(migrationsDir)
      .filter((f) => f.endsWith('.sql'))
      .sort();

    for (const archivo of archivos) {
      if (yaAplicadas.has(archivo)) continue;

      const sql = fs.readFileSync(path.join(migrationsDir, archivo), 'utf8');

      await client.query('BEGIN');
      try {
        await client.query(sql);
        await client.query('INSERT INTO _migrations (archivo) VALUES ($1)', [archivo]);
        await client.query('COMMIT');
      } catch (err) {
        await client.query('ROLLBACK');
        throw new Error(`[migrate] fallo ${archivo}: ${err.message}`);
      }

      console.log(`[migrate] aplicada: ${archivo}`);
    }
  } finally {
    await client.query('SELECT pg_advisory_unlock($1)', [CLAVE_CANDADO]).catch(() => {});
    client.release();
  }
}

export default db;
